spin_manifest_version = 2

[application]
name = "s3-multipart-sample"
version = "0.1.0"
authors = ["Cedric Weber <cedric_oliver.weber@stackit.cloud>"]
description = "Google Workspace Functions"


[[trigger.http]]
route = "/..."
component = "s3-multipart-sample"


[component.s3-multipart-sample]
source = "main.wasm"
allowed_outbound_hosts = ["https://*:*"]
[component.s3-multipart-sample.build]
command = "tinygo build -target=wasip1 -gc=leaking -buildmode=c-shared -no-debug -o main.wasm ."
watch = ["**/*.go", "go.mod"]


