spin_manifest_version = 2

[application]
name = "s3-multipart-sample"
version = "0.1.0"
authors = ["Cedric Weber <cedric_oliver.weber@stackit.cloud>"]
description = "Google Workspace Functions"


[[trigger.http]]
route = "/..."
component = "s3-multipart-sample"


[component.s3-multipart-sample]
source = "main.wasm"
allowed_outbound_hosts = ["https://*:*"]
[component.s3-multipart-sample.build]
command = "tinygo build -target=wasip2 --wit-package $(go list -mod=readonly -m -f '{{.Dir}}' github.com/spinframework/spin-go-sdk/v2)/wit --wit-world http-trigger -o main.wasm ."
watch = ["**/*.go", "go.mod"]


